name: Remove PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

concurrency:
  group: pr-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup PR Preview for PR #${{ github.event.pull_request.number }}
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove